/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.ListaCantantesFamosos;

/**
 *
 * @author Nicolas
 */
public class AgregarCantante extends javax.swing.JFrame {
    
    Fondo fondo = new Fondo();

    /**
     * Creates new form AgregarCantante
     */
    public AgregarCantante() {
        this.setContentPane(fondo);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtfIngresarNombre1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfIngresarNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfDiscoConMasVentas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfTotalVentas = new javax.swing.JTextField();
        btnAgregarCantanteFrame = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 519));
        setMinimumSize(new java.awt.Dimension(650, 519));
        setPreferredSize(new java.awt.Dimension(650, 519));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText(" Agregar Cantante ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        txtfIngresarNombre.setBackground(new java.awt.Color(102, 0, 102));
        txtfIngresarNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfIngresarNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtfIngresarNombre.setBorder(null);
        getContentPane().add(txtfIngresarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 270, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Disco con mas ventas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        txtfDiscoConMasVentas.setBackground(new java.awt.Color(102, 0, 102));
        txtfDiscoConMasVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfDiscoConMasVentas.setForeground(new java.awt.Color(255, 255, 255));
        txtfDiscoConMasVentas.setBorder(null);
        getContentPane().add(txtfDiscoConMasVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 270, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total ventas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        txtfTotalVentas.setBackground(new java.awt.Color(102, 0, 102));
        txtfTotalVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfTotalVentas.setForeground(new java.awt.Color(255, 255, 255));
        txtfTotalVentas.setBorder(null);
        getContentPane().add(txtfTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 270, 40));

        btnAgregarCantanteFrame.setBackground(new java.awt.Color(102, 0, 102));
        btnAgregarCantanteFrame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarCantanteFrame.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCantanteFrame.setText("Agregar");
        btnAgregarCantanteFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAgregarCantanteFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCantanteFrameActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCantanteFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 180, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCantanteFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCantanteFrameActionPerformed

        
        
        try {
            ListaCantantesFamosos.agregarCantante(txtfIngresarNombre.getText(), txtfDiscoConMasVentas.getText(), Integer.parseInt(txtfTotalVentas.getText()));

            JOptionPane.showMessageDialog(null, "Agregado Exitosamente!");

            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente.");
            this.dispose();
        }


    }//GEN-LAST:event_btnAgregarCantanteFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCantante().setVisible(true);
            }
        });
    }
    
    
    
    class Fondo extends JPanel{
    
        private Image imagen;
        
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/imagenFondo.jpg")).getImage();
            
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
            
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCantanteFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtfDiscoConMasVentas;
    private javax.swing.JTextField txtfIngresarNombre;
    private javax.swing.JTextField txtfIngresarNombre1;
    private javax.swing.JTextField txtfTotalVentas;
    // End of variables declaration//GEN-END:variables
}
