/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.CantanteFamoso;
import logica.ListaCantantesFamosos;
import static logica.ListaCantantesFamosos.cantantes;

/**
 *
 * @author Nicolas
 */
public class EditarCantante extends javax.swing.JFrame {

    /**
     * Creates new form EliminarCantante
     */
    public EditarCantante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtfIngresarNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfIndiceEditarCantante = new javax.swing.JTextField();
        btnEditarCantanteFrame = new javax.swing.JButton();
        lbNombresCantantesEditar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        txtfIngresarNombre.setBackground(new java.awt.Color(153, 153, 153));
        txtfIngresarNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtfIngresarNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtfIngresarNombre.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Editar Cantante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantantes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txtfIndiceEditarCantante.setBackground(new java.awt.Color(153, 153, 153));
        txtfIndiceEditarCantante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfIndiceEditarCantante.setForeground(new java.awt.Color(0, 0, 0));
        txtfIndiceEditarCantante.setBorder(null);
        txtfIndiceEditarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIndiceEditarCantanteActionPerformed(evt);
            }
        });
        jPanel1.add(txtfIndiceEditarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, 30));

        btnEditarCantanteFrame.setBackground(new java.awt.Color(153, 153, 153));
        btnEditarCantanteFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarCantanteFrame.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarCantanteFrame.setText("Editar");
        btnEditarCantanteFrame.setBorder(null);
        btnEditarCantanteFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCantanteFrameActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarCantanteFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, 30));

        lbNombresCantantesEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNombresCantantesEditar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNombresCantantesEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 440, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Indice");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarCantanteFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCantanteFrameActionPerformed

        EditarDatosCantante editarDatosCantante = new EditarDatosCantante();
        try {

            int ind = Integer.parseInt(txtfIndiceEditarCantante.getText());
            CantanteFamoso cantanteSeleccionado = cantantes.get(ind - 1);
            CantanteFamoso cantanteSeleccionado2 = ListaCantantesFamosos.cantantesDeMayorAMenor.get(ind - 1);

            editarDatosCantante.setLocationRelativeTo(null);
            editarDatosCantante.setResizable(false);
            editarDatosCantante.setVisible(true);

            editarDatosCantante.getLbNuevoNombreCantante().setText(cantanteSeleccionado.getNombre());
            editarDatosCantante.getLbNuevoDiscoVentasEditar().setText(cantanteSeleccionado.getDiscoConMasVentas());
            editarDatosCantante.getLbNuevoNumeroVisitas().setText(Integer.toString(cantanteSeleccionado.getTotalVentas())); 

            
            this.dispose();
//            JOptionPane.showMessageDialog(null, "Editado Exitosamente!");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Ingrese algo valido.");
            this.dispose();
        }


    }//GEN-LAST:event_btnEditarCantanteFrameActionPerformed

    private void txtfIndiceEditarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIndiceEditarCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIndiceEditarCantanteActionPerformed

    public static void setTxtfnombreEliminarCantante(JTextField txtfnombreEliminarCantante) {
        EditarCantante.txtfIndiceEditarCantante = txtfnombreEliminarCantante;
    }

    public static JTextField getTxtfnombreEliminarCantante() {
        return txtfIndiceEditarCantante;
    }

    public JLabel getLbNombresCantantesEditar() {
        return lbNombresCantantesEditar;
    }

    public void setLbNombresCantantesEditar(JLabel lbNombresCantantesEditar) {
        this.lbNombresCantantesEditar = lbNombresCantantesEditar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCantante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCantanteFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNombresCantantesEditar;
    public static javax.swing.JTextField txtfIndiceEditarCantante;
    private javax.swing.JTextField txtfIngresarNombre;
    // End of variables declaration//GEN-END:variables

    public JLabel getLbNombresCantantes() {
        return lbNombresCantantesEditar;
    }

    public void setLbNombresCantantes(JLabel lbNombresCantantes) {
        this.lbNombresCantantesEditar = lbNombresCantantes;
    }
}
