/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import logica.ListaCantantesFamosos;

/**
 *
 * @author Nicolas
 */
public class EliminarCantante extends javax.swing.JFrame {

    Fondo fondo = new Fondo();

    /**
     * Creates new form EliminarCantante
     */
    public EliminarCantante() {
        
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtfIngresarNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfnombreEliminarCantante = new javax.swing.JTextField();
        btnEliminarCantante = new javax.swing.JButton();
        lbNombresCantantes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        txtfIngresarNombre.setBackground(new java.awt.Color(153, 153, 153));
        txtfIngresarNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtfIngresarNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtfIngresarNombre.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(613, 497));
        setMinimumSize(new java.awt.Dimension(613, 497));
        setPreferredSize(new java.awt.Dimension(613, 497));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText(" Eliminar Cantante ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantantes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtfnombreEliminarCantante.setBackground(new java.awt.Color(102, 0, 102));
        txtfnombreEliminarCantante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfnombreEliminarCantante.setForeground(new java.awt.Color(255, 255, 255));
        txtfnombreEliminarCantante.setBorder(null);
        txtfnombreEliminarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnombreEliminarCantanteActionPerformed(evt);
            }
        });
        getContentPane().add(txtfnombreEliminarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 210, 40));

        btnEliminarCantante.setBackground(new java.awt.Color(102, 0, 102));
        btnEliminarCantante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarCantante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCantante.setText("Eliminar");
        btnEliminarCantante.setBorder(null);
        btnEliminarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCantanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 180, 50));

        lbNombresCantantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNombresCantantes.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbNombresCantantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 510, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Indice");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCantanteActionPerformed

        try {
            ListaCantantesFamosos.eliminarCantanteJframe(Integer.parseInt(txtfnombreEliminarCantante.getText()));

            JOptionPane.showMessageDialog(null, "Eliminado Exitosamente!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos bien.");
            this.dispose();
        }


    }//GEN-LAST:event_btnEliminarCantanteActionPerformed

    private void txtfnombreEliminarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnombreEliminarCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnombreEliminarCantanteActionPerformed

    public static void setTxtfnombreEliminarCantante(JTextField txtfnombreEliminarCantante) {
        EliminarCantante.txtfnombreEliminarCantante = txtfnombreEliminarCantante;
    }

    public static JTextField getTxtfnombreEliminarCantante() {
        return txtfnombreEliminarCantante;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCantante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCantante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbNombresCantantes;
    private javax.swing.JTextField txtfIngresarNombre;
    public static javax.swing.JTextField txtfnombreEliminarCantante;
    // End of variables declaration//GEN-END:variables

    public JLabel getLbNombresCantantes() {
        return lbNombresCantantes;
    }

    public void setLbNombresCantantes(JLabel lbNombresCantantes) {
        this.lbNombresCantantes = lbNombresCantantes;
    }

    class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/imagenFondo.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }

    }
}
