/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import logica.CantanteFamoso;
import logica.ListaCantantesFamosos;

/**
 *
 * @author Nicolas
 */
public class ListaOrdenada extends javax.swing.JFrame {
    
    Fondo fondo = new Fondo();

    DefaultTableModel modelo = new DefaultTableModel();

    String[] columnas = {"Nombre", "Disco mas vendido", "Numero ventas"};

    /**
     * Creates new form Pantalla
     *
     *
     */
    public ListaOrdenada() {
        this.setContentPane(fondo);
        
        initComponents();


        modelo.setColumnIdentifiers(columnas);

        tablaOrdenadaCantantes.setModel(modelo);

        tablaOrdenadaCantantes.setRowHeight(40);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolverInicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenadaCantantes = new javax.swing.JTable();
        btnActualizarTablaOrdenada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText(" Top global de vistas ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        btnVolverInicio.setBackground(new java.awt.Color(102, 0, 102));
        btnVolverInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverInicio.setText("Volver");
        btnVolverInicio.setBorder(null);
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 220, 50));

        tablaOrdenadaCantantes.setBackground(new java.awt.Color(0, 0, 0));
        tablaOrdenadaCantantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tablaOrdenadaCantantes.setForeground(new java.awt.Color(255, 255, 255));
        tablaOrdenadaCantantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaOrdenadaCantantes.setGridColor(new java.awt.Color(153, 0, 153));
        tablaOrdenadaCantantes.setMaximumSize(new java.awt.Dimension(800, 3231312));
        tablaOrdenadaCantantes.setMinimumSize(new java.awt.Dimension(800, 600));
        tablaOrdenadaCantantes.setPreferredSize(new java.awt.Dimension(800, 600));
        jScrollPane1.setViewportView(tablaOrdenadaCantantes);
        if (tablaOrdenadaCantantes.getColumnModel().getColumnCount() > 0) {
            tablaOrdenadaCantantes.getColumnModel().getColumn(0).setResizable(false);
            tablaOrdenadaCantantes.getColumnModel().getColumn(1).setResizable(false);
            tablaOrdenadaCantantes.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 690, 410));

        btnActualizarTablaOrdenada.setBackground(new java.awt.Color(102, 0, 102));
        btnActualizarTablaOrdenada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizarTablaOrdenada.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarTablaOrdenada.setText("Actualizar tabla");
        btnActualizarTablaOrdenada.setBorder(null);
        btnActualizarTablaOrdenada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaOrdenadaActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarTablaOrdenada, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 220, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarTabla(ArrayList lista) {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Nombre", "Disco mas vendido", "Total Venta"},
                0);

        Iterator<CantanteFamoso> iterator = ListaCantantesFamosos.cantantesDeMayorAMenor.iterator();

        while (iterator.hasNext()) {
            CantanteFamoso cantante = iterator.next();
            Object[] fila = {cantante.getNombre(), cantante.getDiscoConMasVentas(), cantante.getTotalVentas()};
            modelo.addRow(fila);
        }
        tablaOrdenadaCantantes.setModel(modelo);

    }


    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed

        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioActionPerformed

    private void btnActualizarTablaOrdenadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaOrdenadaActionPerformed

        ListaCantantesFamosos.organizarMayoraMenor(ListaCantantesFamosos.cantantesDeMayorAMenor);

        if (ListaCantantesFamosos.cantantesDeMayorAMenor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Aun no hay cantantes.");
        } else {
            llenarTabla(ListaCantantesFamosos.cantantesDeMayorAMenor);
        }


    }//GEN-LAST:event_btnActualizarTablaOrdenadaActionPerformed

    
        
    class Fondo extends JPanel{
    
        private Image imagen;
        
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/imagenFondo.jpg")).getImage();
            
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
            
        }
    
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTablaOrdenada;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaOrdenadaCantantes;
    // End of variables declaration//GEN-END:variables
}
