/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import logica.CantanteFamoso;
import logica.ListaCantantesFamosos;

/**
 *
 * @author Nicolas
 */
public class ListaOrdenada extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    String[] columnas = {"Nombre", "Disco mas vendido", "Numero ventas"};

    /**
     * Creates new form Pantalla
     *
     *
     */
    public ListaOrdenada() {
        initComponents();
//        llenarTabla(lista);

        modelo.setColumnIdentifiers(columnas);

        tablaOrdenadaCantantes.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVolverInicio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenadaCantantes = new javax.swing.JTable();
        btnActualizarTablaOrdenada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ejercicio Cantantes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Volver");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, -1));

        btnVolverInicio.setBackground(new java.awt.Color(153, 153, 153));
        btnVolverInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolverInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicio.setText("Volver");
        btnVolverInicio.setBorder(null);
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Actualizar tabla");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        tablaOrdenadaCantantes.setBackground(new java.awt.Color(153, 153, 153));
        tablaOrdenadaCantantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaOrdenadaCantantes.setForeground(new java.awt.Color(0, 0, 0));
        tablaOrdenadaCantantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tablaOrdenadaCantantes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        btnActualizarTablaOrdenada.setBackground(new java.awt.Color(153, 153, 153));
        btnActualizarTablaOrdenada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarTablaOrdenada.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarTablaOrdenada.setText("Actualizar");
        btnActualizarTablaOrdenada.setBorder(null);
        btnActualizarTablaOrdenada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaOrdenadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarTablaOrdenada, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarTabla(ArrayList lista) {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Nombre", "Disco mas vendido", "Total Venta"},
                0);

        Iterator<CantanteFamoso> iterator = ListaCantantesFamosos.cantantesDeMayorAMenor.iterator();

        while (iterator.hasNext()) {
            CantanteFamoso cantante = iterator.next();
            Object[] fila = {cantante.getNombre(), cantante.getDiscoConMasVentas(), cantante.getTotalVentas()};
            modelo.addRow(fila);
        }
        tablaOrdenadaCantantes.setModel(modelo);

    }


    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed

        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioActionPerformed

    private void btnActualizarTablaOrdenadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaOrdenadaActionPerformed

        
        
        ListaCantantesFamosos.organizarMayoraMenor(ListaCantantesFamosos.cantantesDeMayorAMenor);
        
        llenarTabla(ListaCantantesFamosos.cantantesDeMayorAMenor);
        
        
        
    }//GEN-LAST:event_btnActualizarTablaOrdenadaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTablaOrdenada;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaOrdenadaCantantes;
    // End of variables declaration//GEN-END:variables
}
